# -*- coding: utf-8 -*-
"""RK4 para resolução de EDOs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k95NrmSPw15v7Q8rNdsBksfzTphe-zcV
"""

import numpy as np
import matplotlib.pyplot as plt

def rk4_2_ordem(f, t0, tf, y0, dy0, h):
    """
    Resolve uma EDO de segunda ordem da forma:
        y'' = f(t, y, y')

    usando o método de Runge-Kutta de 4ª ordem.

    Parâmetros:
        f   : função f(t, y, y')
        t0  : tempo inicial
        tf  : tempo final
        y0  : y(t0)
        dy0 : y'(t0)
        h   : passo

    Retorna:
        t_vals -> Lista de variaveis de t, y_vals -> Lista de variaveis da função y
        Cria o modelo da solução numérica da EDO.
    """

    N = int((tf - t0) / h)

    t_vals = np.zeros(N + 1)
    y_vals = np.zeros(N + 1)

    t = t0
    y = y0
    dy = dy0

    t_vals[0] = t
    y_vals[0] = y

    for i in range(N):
        # Sistema equivalente
        def f1(t, y, dy): return dy
        def f2(t, y, dy): return f(t, y, dy)

        k1_y = h * f1(t, y, dy)
        k1_dy = h * f2(t, y, dy)

        k2_y = h * f1(t + h/2, y + k1_y/2, dy + k1_dy/2)
        k2_dy = h * f2(t + h/2, y + k1_y/2, dy + k1_dy/2)

        k3_y = h * f1(t + h/2, y + k2_y/2, dy + k2_dy/2)
        k3_dy = h * f2(t + h/2, y + k2_y/2, dy + k2_dy/2)

        k4_y = h * f1(t + h, y + k3_y, dy + k3_dy)
        k4_dy = h * f2(t + h, y + k3_y, dy + k3_dy)

        y += (k1_y + 2*k2_y + 2*k3_y + k4_y) / 6
        dy += (k1_dy + 2*k2_dy + 2*k3_dy + k4_dy) / 6
        t += h

        t_vals[i+1] = t
        y_vals[i+1] = y

    return t_vals, y_vals